name: stcar
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.8.4
  recase: ^4.1.0
  flutter_svg: ^2.0.6
  carousel_slider: ^4.2.1
  http: ^1.0.0
  connectivity_plus: ^4.0.1
  get: ^4.6.5
  intl: ^0.18.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/anim/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/sounds/
    - assets/videos/

#  fonts:
#
#    - family: FontFamilyName
#      fonts:
#        - asset: assets\fonts\name.extension



